### ISSUE TITLE
Change all cursor types with state change

### ISSUE THREAD

**Issue by justmytwospence** [gabesoft/evil-mc#10]
Currently, when multiple cursors are enabled and you switch to insert state, only the real cursor changes to the cursor style set up for the insert state. It would be cool if all of the cursors mirrored the shape of the real one.

**Comment by gabesoft** [comment]
Yeah that's something I wanted too. I just haven't figured out how to do it yet. I'll take another look when I get a chance.

**Comment by PythonNut** [comment]
This is one thing that could easily be propagated to the old `multiple-cursors` implementation, if done.

**Comment by gabesoft** [comment]
This should be fixed now
