### ISSUE TITLE
fake cursors not visible right after selection to cursors

### ISSUE THREAD

**Issue by duianto** [gabesoft/evil-mc#103]
#### Description :octocat:
Creating cursors from a selection doesn't show the fake cursors until one exits to normal state or moves the cursors `C-f` `C-b` in insert state.

#### Reproduction guide :beetle:
- open the scratch buffer
- type:
```
abc
abc
abc
```
- with the cursor on the last line, press `v` to start a char selection
- press `k` twice to move to the first line
- press `grI` or `grA`

*Observed behaviour:* :eyes: :broken_heart:
#### `grI`

![beg](https://user-images.githubusercontent.com/13420573/69546538-3a8b3700-0f94-11ea-98fe-5c66bc5677a2.png)

The cursors seem to be there, because they are changing the color of the first letters `a` with the fake cursor color.

The cursors appear after pressing `Esc`:

![beg esc](https://user-images.githubusercontent.com/13420573/69546570-4a0a8000-0f94-11ea-8026-86f5c8681aa8.png)

The cursors also appear if they are moved forwards `C-f` (or backwards `C-b`):

![beg forward char](https://user-images.githubusercontent.com/13420573/69548242-44626980-0f97-11ea-91c6-b3be07dfd591.png)

#### `grA`

![end](https://user-images.githubusercontent.com/13420573/69546600-568ed880-0f94-11ea-8865-56c37b6446e8.png)

The cursors appear after pressing `Esc`:

![end esc](https://user-images.githubusercontent.com/13420573/69546614-60184080-0f94-11ea-9b36-1e0abeae3712.png)

### Without Spacemacs:

The cursors are visible without Spacemacs:

![without spacemacs beg](https://user-images.githubusercontent.com/13420573/69547791-7d4e0e80-0f96-11ea-82a7-b9af72564e7a.png)

But the first characters are covered, as if the cursors were in normal state.

Moving them forwards `C-f` seems to update them and now the following characters are pushed one step to the right:

![without spacemacs beg forward char](https://user-images.githubusercontent.com/13420573/69547899-aa022600-0f96-11ea-872d-30bf43b7508c.png)

*Expected behaviour:* :heart: :smile:

The fake cursors should be visible right after creating the cursors from a selection.

#### System Info :computer:
- OS: windows-nt
- Emacs: 27.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. b59f8a311)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey
 (auto-completion :variables auto-completion-return-key-behavior nil auto-completion-complete-with-key-sequence nil auto-completion-complete-with-key-sequence "jk")
 (colors :variables)
 command-log emacs-lisp git helm json java javascript markdown multiple-cursors
 (org :variables)
 python react shell spell-checking syntax-checking treemacs typescript version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY W32NOTIFY ACL GNUTLS LIBXML2 HARFBUZZ ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS PDUMPER LCMS2 GMP

**Comment by twlz0ne** [comment]
``` elisp
(setq evil-mc-enable-bar-cursor nil)
(set-face-background 'evil-mc-cursor-default-face (face-background 'highlight))
```

**Comment by duianto** [comment]
This seems to have been fixed since it was reported.
The cursors appear right after pressing: `grI` or `grA`

<details><summary>
Windows 10, System Info (Click to expand)
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 234144853)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion autohotkey emacs-lisp git helm multiple-cursors
                 (org :variables org-agenda-files
                      '("c:/Users/username/org/"))
                 shell spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY W32NOTIFY ACL GNUTLS LIBXML2 HARFBUZZ ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS JSON PDUMPER LCMS2 GMP

</pre>
</details>
