### ISSUE TITLE
key-chords do not work

### ISSUE THREAD

**Issue by PythonNut** [gabesoft/evil-mc#12]
Given the following:

```emacs
(key-chord-define evil-insert-state-map "jj" #'evil-normal-state)
```
When I execute <kbd>jj</kbd> to enter normal state, I get misaligned cursors and the following error:

> Error in pre-command-hook `(evil-mc-begin-command-save)`: `(user-error "Key sequence contains no complete binding")`
evil-mc Failed to execute `nil` with error: Keyboard macro terminated by a command ringing the bell

This is due to the way `key-chord` handles keyboard macros.

From the docs:

> When recording keyboard macros, the time between keyboard inputs are not recorded. Thus, the `key-chord-input-method` cannot know for sure if two keys in a macro was a chord or not. The current solution remembers the first key of the chords typed during macro recording, and keys that match those (and are defined as chords) are considered key-chords during macro execution. This knowledge is not saved with `name-last-kbd-macro`, so they may execute wrong if they contain pair of keys that match defined chords.

**Comment by gabesoft** [comment]
Yea, I wasn't actually planning on supporting ``key-chord``. Getting the correct key sequence for a command is kind of problematic as it is. With ``key-chord`` that gets even more complicated. I'll think about it but I can't promise anything. For now you could disable ``key-chord`` while the cursors are active by re-defining ``evil-mc-incompatible-minor-modes`` before enabling ``evil-mc-mode``.

**Comment by PythonNut** [comment]
Sure. I'll leave this open, you can close it if at any time you decide that it's not worth the effort.

**Comment by gabesoft** [comment]
I'm closing this for now, as it doesn't look like I'll have time to work on it anytime soon. I'll re-open it when I'll have more time.

**Comment by PythonNut** [comment]
Sure thing.

**Comment by Martinsos** [comment]
I think I am having the same problem -> I use "fd" to exit the insert mode, instead of Esc, and each time I type fd, there remains an "f" in one of the cursors. Is there any way to go around this? Thanks!
