### ISSUE TITLE
Can't execute "change".

### ISSUE THREAD

**Issue by dchrzanowski** [gabesoft/evil-mc#131]
As the title suggests, I can't execute any change operation, something like `ciw` or `ci)`.
I do recall being able to, something must have changed at some stage with "something" that I am unable to track down.

With evil-mc-debug mode on I get:
```
evil-mc There are 2 cursors matching "\_<use-package\_>"
evil-mc Command evil-change c
evil-mc Record-begin ((:undo-list-pointer-pre nil undo-tree-canary) (:evil-state-begin . normal) (:keys-pre-with-count nil evil-change [99] nil) (:keys-pre . [99]) (:name . evil-change))
evil-mc Record-motion pre c [99] normal [2 times]
evil-mc-save-keys: cl-ecase failed: pre-read-key-sequence, (pre post)
evil-mc Record-motion post  [] normal
evil-mc Record-finish ((:undo-list-pointer-post nil undo-tree-canary) (:keys-post-raw . [99]) (:keys-post . []) (:last-input . 99) (:evil-state-end . normal) (:keys-motion-post . []) (:keys-motion-pre . [99]) (:undo-list-pointer-pre nil undo-tree-canary) (:evil-state-begin . normal) (:keys-pre-with-count nil evil-change [99] nil) (:keys-pre . [99]) (:name . evil-change)) evil-change
evil-mc Record-done evil-change pre c post  keys-motion  keys-operator  count nil keys 
``` 

I guess that the interesting part is:
```
evil-mc-save-keys: cl-ecase failed: pre-read-key-sequence, (pre post)
```

I'm on Emacs 28.2, evil 20230303.949 and evil-mc 20220118.122

**Comment by thanhvg** [comment]
I'm having this problem too. I did downgrade/bisect `evil` until `mc` worked. I found this change in evil 
https://github.com/emacs-evil/evil/commit/2b2ba3cbeabe1f239b6b0ebdaddcb68dd158bd1f break `mc`

**Comment by rappie** [comment]
I had the same issue. Many thanks to @thanhvg for the pull request. If you use `use-package` and `straight` you can use the config below.

```elisp
  (use-package evil-mc
    :straight
      (evil-mc :type git :flavor melpa :host github :repo "gabesoft/evil-mc"
          :fork (:host github :repo "thanhvg/evil-mc"))
    :config
      (global-evil-mc-mode  1))
```

(I'm no elisp expert, feel free to let me know if i'm doing something wrong :slightly_smiling_face:)
