### ISSUE TITLE
Is this released under a license?

### ISSUE THREAD

**Issue by brariden** [gabesoft/evil-mc#20]
Hi, I'm working with a company that doesn't allow unlicensed software but I'd really like to try this out.  Is this code released under a specific license?

Thanks in advance!
Bobby

**Comment by gabesoft** [comment]
I didn't add a license. But, if I had to add one it would be MIT

**Comment by vyp** [comment]
You should add it! +1 :-)

**Comment by vyp** [comment]
Thank you @gabesoft!

**Comment by brariden** [comment]
Thanks @gabesoft !!
