### ISSUE TITLE
function definition is void: advice-add

### ISSUE THREAD

**Issue by basveeling** [gabesoft/evil-mc#3]
I'm using evil-mc on spacemacs using emacs 24.3.1 on Ubuntu 14.04 . Whenever I trigger the evil-mc-make-cursor-here command (using g r h), nothing happens and the following error appears in *messages*:

`evil-mc-initialize-active-state: Symbol's function definition is void: advice-add`

**Comment by gabesoft** [comment]
I wonder if you're using an older version of evil. During the initialize it's trying to add advices for two functions ``evil-repeat-keystrokes`` and ``evil-repeat-motion``. Are both of those functions available in your setup?

**Comment by basveeling** [comment]
I think so, if I run `(evil-repeat-keystrokes)` from the `ielm` lisp shell, i get a note about missing arguments, same for the `evil-repeat-motion` command.

**Comment by gabesoft** [comment]
Then maybe it's a different problem. What happens if you run evil-mc-mode interactively in a buffer where evil-mode is enabled and then try to create some cursors?

**Comment by bmag** [comment]
Just passing through, `advice-add` was added to Emacs in version 24.4, so it doesn't exist in 24.3.1. For older versions there is `defadvice`.

**Comment by gabesoft** [comment]
@bmag Thanks, that makes sense. I'll add a fix to check for ``advice-add`` and use `defadvice`` if it doesn't exist.

**Comment by gabesoft** [comment]
Actually I'll just update the docs to require emacs version 24.4 or above since there may be other problems on older versions.

**Comment by basveeling** [comment]
Ubuntu's 14.04 LTS release includes Emacs at 24.3, and some people (including myself) are not in the position to upgrade. If I plainly comment out the advice-add functions, the plugin seems to work pretty well. Any chance you would consider adding support for 24.3 as well :)?

**Comment by gabesoft** [comment]
I'll replace advice-add with defadvice ... And let's hope there are no other issues.

**Comment by basveeling** [comment]
Thanks :+1:! Let me know if you need any help with testing.

**Comment by gabesoft** [comment]
Added a fix. Hope it works for you now.

**Comment by basveeling** [comment]
Thanks! I tried installing the package from MELPA, which seems to be up to date with this repo, and I'm getting the error:
`error Package `emacs-24.4' is unavailable`

**Comment by gabesoft** [comment]
I updated the required emacs version.
