### ISSUE TITLE
fake bar cursors

### ISSUE THREAD

**Issue by Dickby** [gabesoft/evil-mc#31]
in magnars multiple-cursors mode, he recently added support for fake bar cursors.
https://github.com/magnars/multiple-cursors.el/commit/8413969a97343d1270a3c70252e4ca2eb4e79c36
It would be nice to have this feature in evil-mc too.
related to issue #10

**Comment by gabesoft** [comment]
Nice, I'll look into implementing this when I get a chance.

**Comment by gabesoft** [comment]
@Dickby thanks for the pull request. Merged.
