### ISSUE TITLE
evil-mc-make-and-goto-next-match not work properly

### ISSUE THREAD

**Issue by DogLooksGood** [gabesoft/evil-mc#4]
`C-n` after expand-region or evil-mc-make-and-goto-next-match called when cursor is not at the end of selection, it will make extra cursor at the beginning of the first occurrence.

**Comment by gabesoft** [comment]
It should work properly as long as you create all cursors you need before moving the cursors. I'll add a fix to skip making cursors on any region that contains a cursor.

**Comment by gabesoft** [comment]
Here's a some more clarification. ``evil-mc-make-and-goto-next-match`` is meant to be used for creating cursors. If you just want to navigate through existing cursors use ``evil-mc-make-and-goto-next-cursor`` and ``evil-mc-make-and-goto-prev-cursor`` which by default are bound to ``M-n`` and ``M-p``

**Comment by DogLooksGood** [comment]
I use 'C-n' to create cursor after select.
[ ] means the cursor.

`C-n` work properly on this condition:
[g]ood
good
good
press `ve`, then press `C-n` to select next 2 words. This work nicely.

But if the my cursor not at the begining of the word, for example:
goo[d]
good
good
press 'vb', then press 'C-n', there will be 4 cursors at last.
[g]oo[d]
goo[d]
goo[d]

Here's my evil packages when testing
evil-20151005.404
evil-leader-20140606.543
evil-mc-20151014.2313

and enabled minor modes: Auto-Composition Auto-Compression Auto-Encryption
Blink-Cursor Electric-Indent Evil Evil-Leader Evil-Local Evil-Mc
File-Name-Shadow Font-Lock Global-Evil-Leader Global-Evil-Mc
Global-Font-Lock Global-Undo-Tree Line-Number Mac-Mouse-Wheel Menu-Bar
Override-Global Tool-Bar Tooltip Transient-Mark Undo-Tree

**Comment by gabesoft** [comment]
Yes, I see the problem now. I will fix it soon.

**Comment by DogLooksGood** [comment]
It works now, thanks very much! :+1:
