### ISSUE TITLE
Misaligned cursors in insert mode

### ISSUE THREAD

**Issue by AndreaOrru** [gabesoft/evil-mc#49]
Spawning some cursors in normal mode using C-n:
<img width="106" alt="1" src="https://cloud.githubusercontent.com/assets/3673952/23759776/06968bec-04ee-11e7-8443-64fb53c06460.png">
All good for now.

But when entering insert mode:
<img width="107" alt="2" src="https://cloud.githubusercontent.com/assets/3673952/23759777/077da4d2-04ee-11e7-922f-1863baa8115a.png">

Any idea of what's going on?
It looks like the "fake bar" that should act as cursor is taking up an entire character's space.

**Comment by gabesoft** [comment]
When running emacs in terminal this is the expected behavior. When running the gui version of emacs this should not happen.

**Comment by AndreaOrru** [comment]
I'm running this the GUI version for OSX.

**Comment by gabesoft** [comment]
I wonder if it has anything to do with the font you're using. I'm using spacemacs and in the GUI version the bar cursors look fine. I'm assuming that you're on the latest emacs version, right?

**Comment by gabesoft** [comment]
As a fix I've added a variable named `evil-mc-enable-bar-cursor` that you can use to turn off the bar cursors in this commit a17ecb87e8c681e05837514160a98efbea141120 
It defaults to `t` but you can set it to `nil` to get the default cursor face for the fake cursors.

**Comment by gabesoft** [comment]
I'm going to close this as I think that the `evil-mc-enable-bar-cursor` setting solves the problem.

**Comment by AndreaOrru** [comment]
That's good enough I guess. Thanks!
