### ISSUE TITLE
FR: a way to add new cursors by clicking

### ISSUE THREAD

**Issue by milkypostman** [gabesoft/evil-mc#56]
I have been pausing mc, then moving to different positions to add a new cursor, but I find this to be tedious. 

it would be nice to have a way to add cursors by clicking. the normal `multiple-cursors` has an `add-cursor-on-click` function that does this.

i will see if I can look into it but time always.

**Comment by gabesoft** [comment]
That sounds like a good idea. I'll try to look into it also when I get a chance

**Comment by gabesoft** [comment]
I tentatively ported the functionality from `multiple-cursors`. To use it just set up a key binding like this
`(global-set-key (kbd "C-S-<mouse-1>") 'evil-mc-toggle-cursor-on-click)`. Let me know if you run into any issues.

**Comment by milkypostman** [comment]
Amazing. I'll give it a shot!

**Comment by milkypostman** [comment]
seems to work great. thanks so much!
