### ISSUE TITLE
Modeline indicator, background color, readability

### ISSUE THREAD

**Issue by duianto** [gabesoft/evil-mc#57]
The evil-mc modeline indicator, can (depending on the theme) make it impossible or very hard to read.

It looks like this:
- Top: Emacs with evil-mc installed
- Middle: Spacemacs with the spacemacs-dark theme (default)
- Bottom: Spacemacs with the spacemacs-light theme

![evil-mc-modeline-indicator-colors](https://cloud.githubusercontent.com/assets/13420573/25521131/c3ac8b50-2bfe-11e7-8117-8c16e0a66088.png)

The background color is the same as the cursors current state color.

In Spacemacs:
- insert state changes the background to Strong green (#66CD00):
![evil-mc-modeline-indicator-insert-state](https://cloud.githubusercontent.com/assets/13420573/25527870/15d0017a-2c1b-11e7-89cb-df5d23502ccf.png)

- visual state changes the background to Gray (#BEBEBE):
![evil-mc-modeline-indicator-visual-state](https://cloud.githubusercontent.com/assets/13420573/25527875/20390d8c-2c1b-11e7-8f22-26eb838e5111.png)

### System info:
evil-mc 0.0.3
Spacemacs 0.200.9

- **System 1**:
Emacs 25.1.1
Windows 10
 
- **System 2**: (Virtual box on System 1)
Emacs 26.0.50
Ubuntu 16.10

**Comment by gabesoft** [comment]
Thanks for reporting

**Comment by gabesoft** [comment]
I think this is also fixed by #64. Is that right?
