### ISSUE TITLE
Variable, if single cursor, hide mode line "emc" text

### ISSUE THREAD

**Issue by duianto** [gabesoft/evil-mc#58]
### Description
In Spacemacs there's a reassignment of the `evil-mc-mode-line` variable, without the `emc` text, when `evil-mc-mode` is enabled and there's only one cursor.
https://github.com/syl20bnr/spacemacs/blob/df408fcd2626883b942fd6204fe00e780582d9f8/layers/%2Bspacemacs/spacemacs-evil/packages.el#L114

### Issue
But anyone that wants to show the `emc` text, when there's only one cursor, needs to add several lines to the `dotspacemacs/user-config` section of their  `.spacemacs` file.

### A possible solution
This could be simplified to a single line, if evil-mc had a variable that shows or hides the `emc` text when there's only one cursor.

Maybe it could be called something like this:
`evil-mc-single-cursor-mode-line-text`
or
`evil-mc-mode-line-text-single-cursor`
or something better.

**Comment by gabesoft** [comment]
Fixed by #64
