### ISSUE TITLE
"undo branch point" message on redo

### ISSUE THREAD

**Issue by edrex** [gabesoft/evil-mc#6]
Hi, just testing this via spacemacs.

When I make an edit via mc insert mode, then undo `u` , then redo `Ctrl-R` , I see the message

```
Undo branch point!
```

On second redo, the inserts are redone. So not fatal. Any idea why that's happening?

**Comment by gabesoft** [comment]
Not sure why that is, but I've noticed the message as well but I'm my case the redo is happening on the first Ctrl-R.  I'll look into it.

**Comment by edrex** [comment]
Just tested and I'm not seeing the message + no action on first redo after MC insert anymore
