### ISSUE TITLE
Arbitrary commands?

### ISSUE THREAD

**Issue by Ambrevar** [gabesoft/evil-mc#65]
From my understanding, only the limited set of `evil-mc-known-commands.el` is available, anything else will apply to one cursor only.
I miss features, such as `evil-search-forward`, `capitalize-word`, `just-one-space` and many more.
Reimplementating all of Emacs' editing features just for this mode does not seem like a viable option.

Is it a limitation due to evil-mode? github.com/magnars/multiple-cursors.el is able to run arbitrary Emacs commands, only some Evil commands fail somehow.

Any take on this?

**Comment by gabesoft** [comment]
Most of those commands can be added to evil-mc-known-commands in a pretty trivial way. Yes the limitation is due to evil mode. Although, there may be a way to implement arbitrary commands, I'm just not aware of it.

**Comment by gabesoft** [comment]
Actually, `evil-search-forward` is a known command but seems broken at the moment. I'll take a look when I have some time.

**Comment by gabesoft** [comment]
There doesn't seem to be an easy way to support search commands such as `evil-search-forward` and `evil-search-backward` so I made a note of it in the README. I may revisit this when I have more time or I'd be happy to accept pull requests for those. I added `capitalize-word` in this commit 506f92dc610906fc279e50c598efe2068161edaa as an example of what's required to add a command to the known commands. I'm closing this for now as there isn't anything more actionable here. Feel free to re-open if you have more thoughts.
