### ISSUE TITLE
Backspace in insert-mode seems to not be working

### ISSUE THREAD

**Issue by rieje** [gabesoft/evil-mc#67]
I visually select a block of text, then narrow it. I do `grm` to mark the strings. When I type some characters, the typed characters are reflected in all cursors as expected. However, if I backspace to delete a character, it only deletes the character from the current line (the line with the real cursor).

If I use vim/evil's `X` to delete the character in visual mode, it deletes it in all lines (so is working properly). So just backspace in insert mode is not working.

**Comment by gabesoft** [comment]
Are there any errors in the `messages` buffer? I wonder if there's a conflict with some minor mode or backspace is running some command overwritten by the major mode that you're in. What major mode are you in when you experience this behavior? Does the same happen in the `fundamental` mode?

**Comment by rieje** [comment]
It happens even if I don't narrow it. [Before](https://ptpb.pw/ACrO7eBvQyGftbC6Ao-prH_xPs0u.png) and [after](https://ptpb.pw/AEQM0GFWihi60urctFsunK4vxt0v.png). There are no errors in the `messages` buffer--only thing related to `evil-mc` is `evil-mc Created 5 cursors matching "\_<setq\_>"`.

It does not happen in `fundamental` mode.

**Comment by gabesoft** [comment]
Can you run `describe-key` and press backspace. See what command it is bound to. On my system that's bound to `evil-backward-char`

**Comment by rieje** [comment]
> DEL (translated from <backspace>) runs the command evil-backward-char (found in
evil-normal-state-map),

**Comment by gabesoft** [comment]
Hmm, then it should work. Try running `evil-mc-executing-debug-on` and backspace again while there are multiple cursors. See if there's any `evil-mc` output in the `messages` buffer.

**Comment by rieje** [comment]
The culprit appears to be [hungry-delete](https://github.com/nflath/hungry-delete). If I don't enable it and restart emacs, then it works.

**Comment by gabesoft** [comment]
That makes sense, `hungry-delete` probably alters the way `evil-backward-char` works. I haven't used before, so I'm not sure what's the real cause of this behavior. But, you can disable it while there are active cursors by re-defining this variable `evil-mc-incompatible-minor-modes`

**Comment by gabesoft** [comment]
Actually, I'll add a fix for `hungry-delete`
