### ISSUE TITLE
evil-mc invokes python-skeleton-if (-for) if cursor is after if (for)

### ISSUE THREAD

**Issue by joonro** [gabesoft/evil-mc#74]
Hi, 

I'm not sure if I'm the only one having this issue - I just tried this and it happens with both `if` and `for`. (I assume other skeleton will work as well). 

For example, when I have two cursors on the `n`'s in the following line:

```python
for 'n' 'n'
```

pressing `c w` invokes `python-skeleton-for` and I get `Iteration spec:` in the mode line.

If I quit with `c-g`, I get `Error in post-command-hook (evil-mc-execute-for-all): (quit . recursive)` message.

**Comment by gabesoft** [comment]
I'm not able to reproduce this issue. It's probably related to your set up. Can you quit with `gru`?

**Comment by joonro** [comment]
Sorry, I should have closed this. In turns out that evil-mode was calling `expand-abbrev` because `expand-abbrev` was in `evil-insert-state-exit-hook`. Having `(setq evil-want-abbrev-expand-on-insert-exit nil)` before loading evil fixed the issue.
