### ISSUE TITLE
Look for help, how to make evil-mc only work in evil-visual-state-mode

### ISSUE THREAD

**Issue by samrayleung** [gabesoft/evil-mc#75]
As title, is there a trigger/variable to make `evil-mc` only work in `evil-visual-state-mode`. Since I always move to the next/previous line with `C-n/C-p`,  but now `evil-mc` takes `C-n/C-p`, could you help me out ?

**Comment by gabesoft** [comment]
You can re-define `evil-mc-key-map`. See an example in [this](https://github.com/syl20bnr/spacemacs/issues/9633) issue

**Comment by samrayleung** [comment]
Thanks for your suggestion :)
