### ISSUE TITLE
Unable to yank and paste multiple cursors

### ISSUE THREAD

**Issue by larebsyed** [gabesoft/evil-mc#81]
Example !cursor selection!
We !are!
We !will!
We !should!

Press y then exit evil-mc-mode
Move to line where you want to paste
Press p

Expected:
are
will
should

Actual:
should

**Comment by gabesoft** [comment]
Yes, you can copy and then move all cursors to the new location (although this may be easy or hard depending on where you want to paste for each cursor). See this gif
![evil-mc-copy-paste](https://user-images.githubusercontent.com/606000/45269882-3552d280-b44a-11e8-8179-ddada25b11c5.gif) for a simple copy/paste

**Comment by larebsyed** [comment]
Yup that is possible in same buffer, but most of the times, my situation demands switching buffer, I don't think that would be possible then, can this be considered as feature in todo?

**Comment by gabesoft** [comment]
I'm not sure I can consider this as a feature since it doesn't seem like something that should be supported by multiple cursors. If you use `evil` mode you can accomplish what you want by using registers.

**Comment by larebsyed** [comment]
I do use evil, But I am not sure how I can achieve this without visiting every line separately in evil. 

Secondly, just for helping purposes, this functionality is present [multiple-cursor](https://github.com/magnars/multiple-cursors.el) package but as this package is not very compatible with evil, so I was hoping that this feature can be ported to evil-mc

**Comment by gabesoft** [comment]
Cool, maybe I'll add this functionality when I get a chance.

**Comment by larebsyed** [comment]
Thanks a lot for listening to my request.

**Comment by larebsyed** [comment]
@gabesoft Perfect! Thanks for such quick feature. You are amazing.
