### ISSUE TITLE
How to automatically disable when evil is disabled?

### ISSUE THREAD

**Issue by Silex** [gabesoft/evil-mc#84]
Evil has `evil-emacs-state-modes` to avoid having evil enabled in modes where it does not make sense (e.g `dired`).

It looks like evil-mc does not follow this behavior (it stays enabled in dired). How to get around this?

Right now I'm thinking about using evil hooks but I'm sure this problem is already solved, thus I ask :wink:

**Comment by gabesoft** [comment]
Actually, I'm not sure. I'm using spacemacs and evil mode is enabled even in dired for me. The easiest way to disable it is probably using `evil` hooks.

**Comment by Silex** [comment]
Okay, thanks.
