### ISSUE TITLE
how to support "shift-selection" ?

### ISSUE THREAD

**Issue by yzprofile** [gabesoft/evil-mc#85]
how to support "shift-selection" ? 

https://www.gnu.org/software/emacs/manual/html_node/emacs/Shift-Selection.html

**Comment by gabesoft** [comment]
Shift-selection doesn't work. Only selection through visual mode works.

**Comment by yzprofile** [comment]
hmm. that's the point...
Is it possible to support it ?

**Comment by gabesoft** [comment]
It's possible but it will take quite a bit of work. If you don't use `evil-mode` then you'd be better off using [multiple-cursors](https://github.com/magnars/multiple-cursors.el) which supports `shift-selection`.
