### ISSUE TITLE
How did you generate that "Evil-MC" dripping ascii art?

### ISSUE THREAD

**Issue by peterhadlaw** [gabesoft/evil-mc#9]
Sorry about the noise but I really like that text and was wondering how you generated it? 

Thanks!

**Comment by gabesoft** [comment]
I used this site  http://patorjk.com/software/taag/#p=display&f=Graffiti&t=Type%20Something%20

**Comment by peterhadlaw** [comment]
Thank you sir, again sorry about the noise but I do appreciate the response. I'm going to close this critical, pressing issue.

Oh and of course, thank you for your contribution to the community!!!! :+1:

**Comment by gabesoft** [comment]
No problem. I wish all the issues were like this.
